### ISSUE TITLE
"Custom sdk resources" doesn't work in 3.2.0 version

### ISSUE THREAD

**Issue by SwetyCore** [Jx2f/mhypbase#10]
`[hook] MoleMole__ConfigUtil_LoadJSONStrConfig {StreamingAssets\\MiHoYoSDKRes\\PC\\mihoyo_sdk_res} using the configured value.`
never shows in console.
This means that Custom sdk resources may not be working properly when using 3.2 client

**Comment by Jx2f** [comment]
Does it work properly in 3.4?

**Comment by SwetyCore** [comment]
In 3.4 all worked well.

**Comment by Jx2f** [comment]
i'm adding the `UnityEngine__JsonUtility_FromJson` offsets for 3.2, you can test with the latest commit.

**Comment by SwetyCore** [comment]
All worked well now!!!
