### ISSUE TITLE
Use regex to rewrite urls

### ISSUE THREAD

**Issue by SwetyCore** [Jx2f/mhypbase#11]
This will help people connect servers without  proxy.

### Discussed in https://github.com/Jx2f/mhypbase/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **SwetyCore** February 15, 2023</sup>

```
std::regex pattern("(http[s]?://.+?.com)|(http[s]?://.*?:[0-9]+)");

std::string njson = std::regex_replace(jsonStr, pattern, "http://example.com");

json = il2cpp_string_new(njson.c_str());
```
</div>

**Comment by Jx2f** [comment]
you can impl it yourself.

btw is it possible by defining the auth server urls in sdk resources? i think that's enough for players to connect with private servers without proxy.

**Comment by SwetyCore** [comment]
At first I thought so, but that file is very long, not suitable for writing in the configuration file

**Comment by Xpl0itR** [comment]
You wouldn't need to put the whole file into the config file i don't think. Add an option for server urls in config, read the original file and replace the urls with the ones from config via regex or whatever

**Comment by Jx2f** [comment]
ah, my poor understanding. did you mean using the regex to replacing the urls in sdk resources, sounds interesting.

**Comment by Jx2f** [comment]
updated. you can test with the latest commit now.

**Comment by ksnsk** [comment]
This is great!
The grasscutter can work.
But, hke4-emu + 3.2server can only login account,not into game.
Error: 
Secondary address resolution failed
Not Found version config

Would this be possible?
