### ISSUE TITLE
Add hook for custom "server_pc" config 

### ISSUE THREAD

**Issue by SwetyCore** [Jx2f/mhypbase#8]
This config is in "StreamingAssets\MiHoYoSDKRes\PC\mihoyo_sdk_res" file
Content:
![image](https://user-images.githubusercontent.com/68674499/218663076-8891c83a-b012-4dff-a35b-4b72accd663e.png)

**Comment by Jx2f** [comment]
I added sdk resources customize option in 955c2cf5833c45eeccb4a157a4736df6c37c351d (also fixed some json-related issues). You can test the latest build artifact with your config.
